import {
  CART_01,
  CART_02,
  CART_03,
  CART_04,
} from "../cart-example/cart-example";

export const PRODUCTS = [
  {
    name: "Producto 1",
    price: 100,
    quantity: 2,
    subtotal: 200,
    image: CART_01,
    id: 1,
    description: "Descripción 1",
  },
  {
    name: "Producto 2",
    price: 200,
    quantity: 5,
    subtotal: 200,
    image: CART_02,
    id: 2,
    description: "Descripción 2",
  },
  {
    name: "Producto 2",
    price: 200,
    quantity: 5,
    subtotal: 200,
    image: CART_02,
    id: 2,
    description: "Descripción 2",
  },
  {
    name: "Producto 2",
    price: 200,
    quantity: 5,
    subtotal: 200,
    image: CART_02,
    id: 2,
    description: "Descripción 2",
  },
  {
    name: "Producto 1",
    price: 100,
    quantity: 2,
    subtotal: 200,
    image: CART_01,
    id: 1,
    description: "Descripción 1",
  },
  {
    name: "Producto 1",
    price: 100,
    quantity: 2,
    subtotal: 200,
    image: CART_01,
    id: 1,
    description: "Descripción 1",
  },
  {
    name: "Producto 1",
    price: 100,
    quantity: 2,
    subtotal: 200,
    image: CART_01,
    id: 1,
    description: "Descripción 1",
  },
];
